dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - sklearn
    - matplotlib
    - pandas
    - ctmatching
    - graphviz
    - lifelines
    - seaborn
    - math
    
